[package]
name = "hhzx_cors"
version = "0.1.0"
edition = "2021"
authors = ["hhzx"]
documentation = "axum框架的跨域中间件"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"