//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod article;
pub mod article_tags;
pub mod category;
pub mod comment;
pub mod permissions;
pub mod role_permissions;
pub mod roles;
pub mod tags;
pub mod user;
pub mod user_roles;
