//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::article::Entity as Article;
pub use super::article_tags::Entity as ArticleTags;
pub use super::category::Entity as Category;
pub use super::comment::Entity as Comment;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::tags::Entity as Tags;
pub use super::user::Entity as User;
pub use super::user_roles::Entity as UserRoles;
