//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::article::Entity as Article;
pub use super::category::Entity as Category;
pub use super::comment::Entity as Comment;
pub use super::user::Entity as User;
